import serial
import time

ports = {
    "fpga_out": "COM16",
    "fpga_in": "COM15",
    "laser2": "COM14",
    "laser1": "COM12",
    "x_motor": "COM19",
    "y_motor": "COM18",
}

fpga_out = serial.Serial(ports["fpga_out"], 115200)
fpga_in = serial.Serial(ports["fpga_in"], 115200)
#laser2 = serial.Serial(ports["laser2"], 9600)  # red laser
#laser1 = serial.Serial(ports["laser1"], 9600)  # green laser
#x_motor = serial.Serial(ports["x_motor"], 9600)
#y_motor = serial.Serial(ports["y_motor"], 9600)

fpga_out.name = "fpga_out"
fpga_in.name = "fpga_in"
#laser2.name = "laser2"
#laser1.name = "laser1"
#x_motor.name = "x_motor"
#y_motor.name = "y_motor"


def wait_then_write(interface, cmd, receive_interface=None):
    if receive_interface is None:
        receive_interface = interface
    #input(interface.name + ' ' + str(cmd))
    interface.write(cmd)
    while receive_interface.in_waiting == 0:
        pass
    while receive_interface.in_waiting > 0:
        print(receive_interface.name, receive_interface.readline().rstrip())
    print()


wait_then_write(fpga_out, b"RESET\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MISCRV\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SW_BRUNO 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWBEADCOMPAT 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWLINECOUNT 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWTIME 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"TDINEW_ATS\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWYZ_POS 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"TRAHSEN 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LSEN\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"TDIMASK 24\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZADCAE 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCVGAIN1 500\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCVGAIN2 500\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCVLIM1 3\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCVLIM2 7\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCVPRT1 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCVOFST 250\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCVHTPX 350\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWZLAG 10\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWDITH_SIZE 100\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWDITH_SHIFT 20\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWCEILING 65535\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWDITH_IGAIN 100\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWDITH_IHIST 4\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZSEL 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 30000\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"TDIBB 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDSWPRATE 48\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDPULSRATE 23\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODETMPST 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODE1 3\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDSWPRATE 48\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDPULSRATE 23\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODETMPST 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODE2 3\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODETMPST 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODE1 4\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODETMPST 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"LEDMODE2 4\n", receive_interface=fpga_in)
#wait_then_write(fpga_out, b"", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWLSRSHUT 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"TDIZ_PI_STAGE\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWFTLSR 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX1VL 131072\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"~DOORSOPEN\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX2VL 131072\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1CUR 35\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2CUR 35\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3CUR 35\n", receive_interface=fpga_in)
#wait_then_write(fpga_out, b"", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2VL_UP 10\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOSPIINIT\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX1CUR 35\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2VL_DN 10\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"DOORSSTATE 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOGVAL 0 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX2CUR 35\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2VL 62500\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3VL 62500\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1VL 62500\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZSEL 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWLSRSHUT 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOMVAL 0 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 30000\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RDV_UP\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOGSTEPS 1 1 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RDV_DN\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZSTEP 1288471\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOGVAL 200 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX1HM2\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX2HM2\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2O\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOGVAL 200 130\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOGSTEPS 30 1 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOGSTEPS 30 5000 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2I\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOGSTEPS 30 5000 2\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWLSRSHUT 1\n", receive_interface=fpga_in)
#wait_then_write(fpga_out, b"", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWVIX 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"MIOCOMPR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWVIX 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2VL_UP 20\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2VL_DN 40\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RDV_UP\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RDV_DN\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2O\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2I\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EM2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 13107\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 52428\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZSPEC -25 65493\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 5243\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 4456\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 3670\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 2884\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 2097\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 1311\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 60292\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 61079\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"TDIYEWR 5999999\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 61865\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 62651\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 63438\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZDACW 64224\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZTRG 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZYT 0 3\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZMV 32769\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZTRG 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZYT 0 3\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZMV 64224\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZTRG 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZYT 0 3\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"ZMV 1311\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3HM\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWLSRSHUT 0\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX1HM2\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"EX2HM2\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"SWLSRSHUT 1\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2CR\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T2RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T3RD\n", receive_interface=fpga_in)
wait_then_write(fpga_out, b"T1RD\n", receive_interface=fpga_in)
